#include "arduino_secrets.h"
/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/437c2370-f319-4f68-8e9c-2767145ebe9f
  Arduino IoT Cloud Variables description
  The following variables are automatically generated and updated when changes are made to the Thing
  CloudIlluminance light;
  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <Arduino.h>
#include <hp_BH1750.h>  //  include the library
#define value 500
hp_BH1750 BH1750;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  pinMode(LED_BUILTIN, OUTPUT);
  bool avail = BH1750.begin(BH1750_TO_GROUND);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
  */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();

  BH1750.start();   //starts a measurement
  light = BH1750.getLux(); //  waits until a conversion finished
  Serial.println(light);

  if (value < light)
  {
    offLedChange();
  }
  else
  {
    onLedChange();
  }

}
void offLedChange() {
  digitalWrite(LED_BUILTIN, HIGH);
  // Do something
}
void onLedChange() {
  digitalWrite(LED_BUILTIN, LOW);
  // Do something
}





/*
  Since Light is READ_WRITE variable, onLightChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLightChange()  {
  // Add your code here to act upon Light change
}
